services:
  db-keycloak:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db-kc:/var/lib/mysql

  keycloak-custon:
    image: provider--shoesckick-login:latest
    environment:
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=7080
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://db-keycloak:3306/dbuser?createDatabaseIfNotExist=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_LOG_LEVEL=info
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7088/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command:
      [ "start-dev", "--http-port 7080", "--https-port 7443", "--import-realm" ]
    volumes:
      - ../keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - 7080:7080
      - 7443:7443
    depends_on:
      - db-keycloak
volumes:

  my-db-kc:
  cache:
    driver: local