apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider--shoesclick-login-deployment
  namespace: shoes-eks
spec:
  selector:
    matchLabels:
      app: provider--shoesclick-login
  template: 
    metadata:
        name: provider--shoesclick-login
        labels:
          app: provider--shoesclick-login
    spec:
        containers:
          - name: provider--shoesclick-login-container
            image: $dck-accountid/$dck-repository:provider--shoesclick-login-$githash
            args: ["start-dev"]
            envFrom:
              - configMapRef:
                  name: provider--shoesclick-login-configmap
            ports:
              - name: "http"
                containerPort: 7080
              - name: "https"
                containerPort: 7443
            readinessProbe:
              httpGet:
                path: /realms/master
                port: 7080