apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider--shoesclick-login-deployment
  namespace: shoes-eks
spec:
  selector:
    matchLabels:
      app: provider--shoesclick-login
  template: 
    metadata:
        name: provider--shoesclick-login
        labels:
          app: provider--shoesclick-login
    spec:
        containers:
          - name: provider--shoesclick-login-container
            image: $dck-accountid/$dck-repository:provider--shoesclick-login-$githash
            envFrom:
              - configMapRef:
                  name: provider--shoesclick-login-configmap
            ports:
              - containerPort: 5000
              - containerPort: 9090
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 9090
              initialDelaySeconds: 120
              periodSeconds: 60
              timeoutSeconds: 10
              successThreshold: 1
              failureThreshold: 2
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 9090
              initialDelaySeconds: 120
              periodSeconds: 10
              timeoutSeconds: 10
