apiVersion: v1
kind: Service
metadata: 
  name: svc-provider--shoesclick-login
  namespace: shoes-eks
spec:
  type: LoadBalancer
  selector:
      app: provider--shoesclick-login
  ports:
    - port: 7080
      name: http-5000
      protocol: TCP
      targetPort: 7080
    - port: 7443
      name: http-7443
      protocol: TCP
      targetPort: 7443