apiVersion: v1
kind: Service
metadata: 
  name: shoesclick-login
  namespace: ns-login
spec:
  type: LoadBalancer
  selector:
      app: provider--shoesclick-login
  ports:
    - port: 7080
      name: http-7080
      targetPort: 7080
    - port: 7443
      name: http-sec
      targetPort: 7443